version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: tasks_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      timeout: 10s

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  api:
    build: ./
    command: npm run start:dev
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: app
      DATABASE_PASSWORD: pass
      DATABASE_NAME: tasks_db
      REDIS_HOST: redis
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  db_data:
